QUESTION_BANK = [
    "What's a skill you have that would surprise your teammates?",
    "What's the most unusual job you've ever had?",
    "If you could only eat one meal for the rest of your life, what would it be?",
    "What's a place you've visited that genuinely changed how you see the world?",
    "What's something you believed as a child that turned out to be completely wrong?",
    "If you could have dinner with any historical figure, who would it be and why?",
    "What's the strangest thing you've ever eaten?",
    "What hobby do you wish you had more time for?",
    "What's a movie or book that you think everyone should experience at least once?",
    "If you woke up tomorrow with one new skill mastered, what would you choose?",
    "What's the best advice you've ever received?",
    "What's a small daily habit that has made a surprisingly big difference in your life?",
    "What's something you're genuinely proud of that doesn't belong on a CV?",
    "If your life were a TV show, what genre would it be?",
    "What's a topic you could give a 30-minute talk on with zero preparation?",
    "What's the most remote or off-the-beaten-path place you've ever been?",
    "If you had to switch careers tomorrow, what would you do?",
    "What's a technology or invention you think is truly underrated?",
    "What childhood dream did you actually manage to make happen?",
    "If you could learn any language instantly, which would you choose and why?",
]
